version: '3.7'

services:
  web:
    build: .
    volumes:
      - ./GeoLocatingAPI/:/usr/src/app/
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
    tty: true
  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=geolocatingapi
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=geolocatingapi
    ports:
      - 5432:5432
    tty: true
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
