# Generated by Django 3.1.6 on 2021-02-10 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="geolocationdata",
            old_name="ip_type",
            new_name="type",
        ),
    ]
