# Generated by Django 3.1.6 on 2021-02-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210210_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocationdata',
            name='city',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='geolocationdata',
            name='country_code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='geolocationdata',
            name='country_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='geolocationdata',
            name='ip',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='geolocationdata',
            name='region_code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='geolocationdata',
            name='type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='geolocationdata',
            name='zip',
            field=models.CharField(max_length=10),
        ),
    ]
